stages:
    - build
    - test

before_script:
    - apt-get update -qq && apt-get install -y -qq clang make
    - clang -v

build:
    stage: build
    script:
        - make re

test_libft:
    stage: test
    script:
        - make re -C lib/libft/tests
        - lib/libft/tests/tests

test_libvec:
    stage: test
    script:
        - make re -C lib/libvec/tests
        - lib/libvec/tests/tests
